// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: v1/miiko.proto

package miikov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProblemListGetRequest_SortType int32

const (
	ProblemListGetRequest_SORT_TYPE_UNSPECIFIED  ProblemListGetRequest_SortType = 0
	ProblemListGetRequest_SORT_TYPE_CREATED_TIME ProblemListGetRequest_SortType = 1
	ProblemListGetRequest_SORT_TYPE_ESTIMATION   ProblemListGetRequest_SortType = 2
)

// Enum value maps for ProblemListGetRequest_SortType.
var (
	ProblemListGetRequest_SortType_name = map[int32]string{
		0: "SORT_TYPE_UNSPECIFIED",
		1: "SORT_TYPE_CREATED_TIME",
		2: "SORT_TYPE_ESTIMATION",
	}
	ProblemListGetRequest_SortType_value = map[string]int32{
		"SORT_TYPE_UNSPECIFIED":  0,
		"SORT_TYPE_CREATED_TIME": 1,
		"SORT_TYPE_ESTIMATION":   2,
	}
)

func (x ProblemListGetRequest_SortType) Enum() *ProblemListGetRequest_SortType {
	p := new(ProblemListGetRequest_SortType)
	*p = x
	return p
}

func (x ProblemListGetRequest_SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProblemListGetRequest_SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_miiko_proto_enumTypes[0].Descriptor()
}

func (ProblemListGetRequest_SortType) Type() protoreflect.EnumType {
	return &file_v1_miiko_proto_enumTypes[0]
}

func (x ProblemListGetRequest_SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProblemListGetRequest_SortType.Descriptor instead.
func (ProblemListGetRequest_SortType) EnumDescriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{12, 0}
}

type Category struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId          string   `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryDisplayName string   `protobuf:"bytes,2,opt,name=category_display_name,json=categoryDisplayName,proto3" json:"category_display_name,omitempty"`
	CategorySystemName  string   `protobuf:"bytes,3,opt,name=category_system_name,json=categorySystemName,proto3" json:"category_system_name,omitempty"`
	CategoryOrder       int32    `protobuf:"varint,4,opt,name=category_order,json=categoryOrder,proto3" json:"category_order,omitempty"`
	TopicSize           int32    `protobuf:"varint,5,opt,name=topic_size,json=topicSize,proto3" json:"topic_size,omitempty"`
	ProblemSize         int32    `protobuf:"varint,6,opt,name=problem_size,json=problemSize,proto3" json:"problem_size,omitempty"`
	TopicList           []*Topic `protobuf:"bytes,7,rep,name=topic_list,json=topicList,proto3" json:"topic_list,omitempty"`
}

func (x *Category) Reset() {
	*x = Category{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Category) GetCategoryDisplayName() string {
	if x != nil {
		return x.CategoryDisplayName
	}
	return ""
}

func (x *Category) GetCategorySystemName() string {
	if x != nil {
		return x.CategorySystemName
	}
	return ""
}

func (x *Category) GetCategoryOrder() int32 {
	if x != nil {
		return x.CategoryOrder
	}
	return 0
}

func (x *Category) GetTopicSize() int32 {
	if x != nil {
		return x.TopicSize
	}
	return 0
}

func (x *Category) GetProblemSize() int32 {
	if x != nil {
		return x.ProblemSize
	}
	return 0
}

func (x *Category) GetTopicList() []*Topic {
	if x != nil {
		return x.TopicList
	}
	return nil
}

type Topic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicId          string     `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	TopicDisplayName string     `protobuf:"bytes,2,opt,name=topic_display_name,json=topicDisplayName,proto3" json:"topic_display_name,omitempty"`
	TopicOrder       int32      `protobuf:"varint,3,opt,name=topic_order,json=topicOrder,proto3" json:"topic_order,omitempty"`
	ProblemList      []*Problem `protobuf:"bytes,4,rep,name=problem_list,json=problemList,proto3" json:"problem_list,omitempty"`
}

func (x *Topic) Reset() {
	*x = Topic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *Topic) GetTopicDisplayName() string {
	if x != nil {
		return x.TopicDisplayName
	}
	return ""
}

func (x *Topic) GetTopicOrder() int32 {
	if x != nil {
		return x.TopicOrder
	}
	return 0
}

func (x *Topic) GetProblemList() []*Problem {
	if x != nil {
		return x.ProblemList
	}
	return nil
}

type Problem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProblemId          string `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Url                string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	ProblemDisplayName string `protobuf:"bytes,3,opt,name=problem_display_name,json=problemDisplayName,proto3" json:"problem_display_name,omitempty"`
	Estimation         int32  `protobuf:"varint,4,opt,name=estimation,proto3" json:"estimation,omitempty"`
	TagList            []*Tag `protobuf:"bytes,5,rep,name=tag_list,json=tagList,proto3" json:"tag_list,omitempty"`
}

func (x *Problem) Reset() {
	*x = Problem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Problem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Problem) ProtoMessage() {}

func (x *Problem) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Problem.ProtoReflect.Descriptor instead.
func (*Problem) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{2}
}

func (x *Problem) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *Problem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Problem) GetProblemDisplayName() string {
	if x != nil {
		return x.ProblemDisplayName
	}
	return ""
}

func (x *Problem) GetEstimation() int32 {
	if x != nil {
		return x.Estimation
	}
	return 0
}

func (x *Problem) GetTagList() []*Tag {
	if x != nil {
		return x.TagList
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId       string `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	TopicId          string `protobuf:"bytes,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	TopicDisplayName string `protobuf:"bytes,3,opt,name=topic_display_name,json=topicDisplayName,proto3" json:"topic_display_name,omitempty"`
}

func (x *Tag) Reset() {
	*x = Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{3}
}

func (x *Tag) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Tag) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *Tag) GetTopicDisplayName() string {
	if x != nil {
		return x.TopicDisplayName
	}
	return ""
}

// req/res
type CategoryListGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsRequiredTopic bool `protobuf:"varint,1,opt,name=is_required_topic,json=isRequiredTopic,proto3" json:"is_required_topic,omitempty"`
}

func (x *CategoryListGetRequest) Reset() {
	*x = CategoryListGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryListGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListGetRequest) ProtoMessage() {}

func (x *CategoryListGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListGetRequest.ProtoReflect.Descriptor instead.
func (*CategoryListGetRequest) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryListGetRequest) GetIsRequiredTopic() bool {
	if x != nil {
		return x.IsRequiredTopic
	}
	return false
}

type CategoryListGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryList []*Category `protobuf:"bytes,1,rep,name=category_list,json=categoryList,proto3" json:"category_list,omitempty"`
}

func (x *CategoryListGetResponse) Reset() {
	*x = CategoryListGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryListGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListGetResponse) ProtoMessage() {}

func (x *CategoryListGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListGetResponse.ProtoReflect.Descriptor instead.
func (*CategoryListGetResponse) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryListGetResponse) GetCategoryList() []*Category {
	if x != nil {
		return x.CategoryList
	}
	return nil
}

type CategoryPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId string    `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Category   *Category `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CategoryPostRequest) Reset() {
	*x = CategoryPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryPostRequest) ProtoMessage() {}

func (x *CategoryPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryPostRequest.ProtoReflect.Descriptor instead.
func (*CategoryPostRequest) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryPostRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CategoryPostRequest) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type CategoryPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategoryId string `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
}

func (x *CategoryPostResponse) Reset() {
	*x = CategoryPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CategoryPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryPostResponse) ProtoMessage() {}

func (x *CategoryPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryPostResponse.ProtoReflect.Descriptor instead.
func (*CategoryPostResponse) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{7}
}

func (x *CategoryPostResponse) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type TopicListGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CategorySystemName string `protobuf:"bytes,1,opt,name=category_system_name,json=categorySystemName,proto3" json:"category_system_name,omitempty"`
}

func (x *TopicListGetRequest) Reset() {
	*x = TopicListGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicListGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicListGetRequest) ProtoMessage() {}

func (x *TopicListGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicListGetRequest.ProtoReflect.Descriptor instead.
func (*TopicListGetRequest) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{8}
}

func (x *TopicListGetRequest) GetCategorySystemName() string {
	if x != nil {
		return x.CategorySystemName
	}
	return ""
}

type TopicListGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category  *Category `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	TopicList []*Topic  `protobuf:"bytes,2,rep,name=topic_list,json=topicList,proto3" json:"topic_list,omitempty"`
}

func (x *TopicListGetResponse) Reset() {
	*x = TopicListGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicListGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicListGetResponse) ProtoMessage() {}

func (x *TopicListGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicListGetResponse.ProtoReflect.Descriptor instead.
func (*TopicListGetResponse) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{9}
}

func (x *TopicListGetResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *TopicListGetResponse) GetTopicList() []*Topic {
	if x != nil {
		return x.TopicList
	}
	return nil
}

type TopicPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicId    string `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Topic      *Topic `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	CategoryId string `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
}

func (x *TopicPostRequest) Reset() {
	*x = TopicPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPostRequest) ProtoMessage() {}

func (x *TopicPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPostRequest.ProtoReflect.Descriptor instead.
func (*TopicPostRequest) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{10}
}

func (x *TopicPostRequest) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *TopicPostRequest) GetTopic() *Topic {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *TopicPostRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

type TopicPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicId string `protobuf:"bytes,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
}

func (x *TopicPostResponse) Reset() {
	*x = TopicPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicPostResponse) ProtoMessage() {}

func (x *TopicPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicPostResponse.ProtoReflect.Descriptor instead.
func (*TopicPostResponse) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{11}
}

func (x *TopicPostResponse) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

type ProblemListGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset   int32                          `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit    int32                          `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortType ProblemListGetRequest_SortType `protobuf:"varint,3,opt,name=sort_type,json=sortType,proto3,enum=miiko.v1.ProblemListGetRequest_SortType" json:"sort_type,omitempty"`
}

func (x *ProblemListGetRequest) Reset() {
	*x = ProblemListGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemListGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemListGetRequest) ProtoMessage() {}

func (x *ProblemListGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemListGetRequest.ProtoReflect.Descriptor instead.
func (*ProblemListGetRequest) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{12}
}

func (x *ProblemListGetRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ProblemListGetRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ProblemListGetRequest) GetSortType() ProblemListGetRequest_SortType {
	if x != nil {
		return x.SortType
	}
	return ProblemListGetRequest_SORT_TYPE_UNSPECIFIED
}

type ProblemListGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProblemList []*Problem `protobuf:"bytes,1,rep,name=problem_list,json=problemList,proto3" json:"problem_list,omitempty"`
}

func (x *ProblemListGetResponse) Reset() {
	*x = ProblemListGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemListGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemListGetResponse) ProtoMessage() {}

func (x *ProblemListGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemListGetResponse.ProtoReflect.Descriptor instead.
func (*ProblemListGetResponse) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{13}
}

func (x *ProblemListGetResponse) GetProblemList() []*Problem {
	if x != nil {
		return x.ProblemList
	}
	return nil
}

type ProblemGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProblemId string `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
}

func (x *ProblemGetRequest) Reset() {
	*x = ProblemGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemGetRequest) ProtoMessage() {}

func (x *ProblemGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemGetRequest.ProtoReflect.Descriptor instead.
func (*ProblemGetRequest) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{14}
}

func (x *ProblemGetRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

type ProblemGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Problem *Problem `protobuf:"bytes,1,opt,name=problem,proto3" json:"problem,omitempty"`
}

func (x *ProblemGetResponse) Reset() {
	*x = ProblemGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemGetResponse) ProtoMessage() {}

func (x *ProblemGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemGetResponse.ProtoReflect.Descriptor instead.
func (*ProblemGetResponse) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{15}
}

func (x *ProblemGetResponse) GetProblem() *Problem {
	if x != nil {
		return x.Problem
	}
	return nil
}

type ProblemPostRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProblemId string   `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
	Problem   *Problem `protobuf:"bytes,2,opt,name=problem,proto3" json:"problem,omitempty"`
}

func (x *ProblemPostRequest) Reset() {
	*x = ProblemPostRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemPostRequest) ProtoMessage() {}

func (x *ProblemPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemPostRequest.ProtoReflect.Descriptor instead.
func (*ProblemPostRequest) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{16}
}

func (x *ProblemPostRequest) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

func (x *ProblemPostRequest) GetProblem() *Problem {
	if x != nil {
		return x.Problem
	}
	return nil
}

type ProblemPostResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProblemId string `protobuf:"bytes,1,opt,name=problem_id,json=problemId,proto3" json:"problem_id,omitempty"`
}

func (x *ProblemPostResponse) Reset() {
	*x = ProblemPostResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_miiko_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProblemPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProblemPostResponse) ProtoMessage() {}

func (x *ProblemPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_miiko_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProblemPostResponse.ProtoReflect.Descriptor instead.
func (*ProblemPostResponse) Descriptor() ([]byte, []int) {
	return file_v1_miiko_proto_rawDescGZIP(), []int{17}
}

func (x *ProblemPostResponse) GetProblemId() string {
	if x != nil {
		return x.ProblemId
	}
	return ""
}

var File_v1_miiko_proto protoreflect.FileDescriptor

var file_v1_miiko_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x22, 0xaa, 0x02, 0x0a, 0x08, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x15, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x14,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x69,
	0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x09, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xa7, 0x01, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x44,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0c, 0x70,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0xb6, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x30,
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61,
	0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x70, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x28, 0x0a, 0x08, 0x74, 0x61, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61,
	0x67, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x6f, 0x0a, 0x03, 0x54, 0x61,
	0x67, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x12, 0x2c, 0x0a,
	0x12, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x16, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x11, 0x69, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0f, 0x69, 0x73, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x22, 0x52, 0x0a, 0x17, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73,
	0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0d,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0c, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x66, 0x0a, 0x13, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x12, 0x2e, 0x0a,
	0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x37, 0x0a,
	0x14, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x13, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c,
	0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a,
	0x14, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x76, 0x0a, 0x14, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6d, 0x69, 0x69, 0x6b,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x2e, 0x0a, 0x0a, 0x74, 0x6f, 0x70, 0x69, 0x63,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x69,
	0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x09, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x75, 0x0a, 0x10, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1f, 0x0a,
	0x0b, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x2e,
	0x0a, 0x11, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x22, 0xe9,
	0x01, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x45, 0x0a, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x28, 0x2e, 0x6d, 0x69, 0x69, 0x6b,
	0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x08, 0x73, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x22, 0x5b, 0x0a,
	0x08, 0x53, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x53, 0x4f, 0x52,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x44, 0x5f, 0x54, 0x49, 0x4d, 0x45, 0x10, 0x01,
	0x12, 0x18, 0x0a, 0x14, 0x53, 0x4f, 0x52, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x53,
	0x54, 0x49, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x02, 0x22, 0x4e, 0x0a, 0x16, 0x50, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x69,
	0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x0b, 0x70,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x11, 0x50, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x41,
	0x0a, 0x12, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x22, 0x60, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x22, 0x34, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x50, 0x6f,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72,
	0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x49, 0x64, 0x32, 0xc2, 0x04, 0x0a, 0x0c, 0x4d, 0x69,
	0x69, 0x6b, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58, 0x0a, 0x0f, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x12, 0x20, 0x2e,
	0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0c, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x1d, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0c, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c, 0x69,
	0x73, 0x74, 0x47, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x50,
	0x6f, 0x73, 0x74, 0x12, 0x1a, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55,
	0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74,
	0x12, 0x1f, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f,
	0x62, 0x6c, 0x65, 0x6d, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d,
	0x47, 0x65, 0x74, 0x12, 0x1b, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x62,
	0x6c, 0x65, 0x6d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x4c, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x1c, 0x2e, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d,
	0x50, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6e,
	0x67, 0x65, 0x6e, 0x4d, 0x65, 0x2f, 0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x65, 0x6e, 0x5f, 0x67, 0x6f, 0x2f, 0x76, 0x31, 0x3b,
	0x6d, 0x69, 0x69, 0x6b, 0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_miiko_proto_rawDescOnce sync.Once
	file_v1_miiko_proto_rawDescData = file_v1_miiko_proto_rawDesc
)

func file_v1_miiko_proto_rawDescGZIP() []byte {
	file_v1_miiko_proto_rawDescOnce.Do(func() {
		file_v1_miiko_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_miiko_proto_rawDescData)
	})
	return file_v1_miiko_proto_rawDescData
}

var file_v1_miiko_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_miiko_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_v1_miiko_proto_goTypes = []interface{}{
	(ProblemListGetRequest_SortType)(0), // 0: miiko.v1.ProblemListGetRequest.SortType
	(*Category)(nil),                    // 1: miiko.v1.Category
	(*Topic)(nil),                       // 2: miiko.v1.Topic
	(*Problem)(nil),                     // 3: miiko.v1.Problem
	(*Tag)(nil),                         // 4: miiko.v1.Tag
	(*CategoryListGetRequest)(nil),      // 5: miiko.v1.CategoryListGetRequest
	(*CategoryListGetResponse)(nil),     // 6: miiko.v1.CategoryListGetResponse
	(*CategoryPostRequest)(nil),         // 7: miiko.v1.CategoryPostRequest
	(*CategoryPostResponse)(nil),        // 8: miiko.v1.CategoryPostResponse
	(*TopicListGetRequest)(nil),         // 9: miiko.v1.TopicListGetRequest
	(*TopicListGetResponse)(nil),        // 10: miiko.v1.TopicListGetResponse
	(*TopicPostRequest)(nil),            // 11: miiko.v1.TopicPostRequest
	(*TopicPostResponse)(nil),           // 12: miiko.v1.TopicPostResponse
	(*ProblemListGetRequest)(nil),       // 13: miiko.v1.ProblemListGetRequest
	(*ProblemListGetResponse)(nil),      // 14: miiko.v1.ProblemListGetResponse
	(*ProblemGetRequest)(nil),           // 15: miiko.v1.ProblemGetRequest
	(*ProblemGetResponse)(nil),          // 16: miiko.v1.ProblemGetResponse
	(*ProblemPostRequest)(nil),          // 17: miiko.v1.ProblemPostRequest
	(*ProblemPostResponse)(nil),         // 18: miiko.v1.ProblemPostResponse
}
var file_v1_miiko_proto_depIdxs = []int32{
	2,  // 0: miiko.v1.Category.topic_list:type_name -> miiko.v1.Topic
	3,  // 1: miiko.v1.Topic.problem_list:type_name -> miiko.v1.Problem
	4,  // 2: miiko.v1.Problem.tag_list:type_name -> miiko.v1.Tag
	1,  // 3: miiko.v1.CategoryListGetResponse.category_list:type_name -> miiko.v1.Category
	1,  // 4: miiko.v1.CategoryPostRequest.category:type_name -> miiko.v1.Category
	1,  // 5: miiko.v1.TopicListGetResponse.category:type_name -> miiko.v1.Category
	2,  // 6: miiko.v1.TopicListGetResponse.topic_list:type_name -> miiko.v1.Topic
	2,  // 7: miiko.v1.TopicPostRequest.topic:type_name -> miiko.v1.Topic
	0,  // 8: miiko.v1.ProblemListGetRequest.sort_type:type_name -> miiko.v1.ProblemListGetRequest.SortType
	3,  // 9: miiko.v1.ProblemListGetResponse.problem_list:type_name -> miiko.v1.Problem
	3,  // 10: miiko.v1.ProblemGetResponse.problem:type_name -> miiko.v1.Problem
	3,  // 11: miiko.v1.ProblemPostRequest.problem:type_name -> miiko.v1.Problem
	5,  // 12: miiko.v1.MiikoService.CategoryListGet:input_type -> miiko.v1.CategoryListGetRequest
	7,  // 13: miiko.v1.MiikoService.CategoryPost:input_type -> miiko.v1.CategoryPostRequest
	9,  // 14: miiko.v1.MiikoService.TopicListGet:input_type -> miiko.v1.TopicListGetRequest
	11, // 15: miiko.v1.MiikoService.TopicPost:input_type -> miiko.v1.TopicPostRequest
	13, // 16: miiko.v1.MiikoService.ProblemListGet:input_type -> miiko.v1.ProblemListGetRequest
	15, // 17: miiko.v1.MiikoService.ProblemGet:input_type -> miiko.v1.ProblemGetRequest
	17, // 18: miiko.v1.MiikoService.ProblemPost:input_type -> miiko.v1.ProblemPostRequest
	6,  // 19: miiko.v1.MiikoService.CategoryListGet:output_type -> miiko.v1.CategoryListGetResponse
	8,  // 20: miiko.v1.MiikoService.CategoryPost:output_type -> miiko.v1.CategoryPostResponse
	10, // 21: miiko.v1.MiikoService.TopicListGet:output_type -> miiko.v1.TopicListGetResponse
	12, // 22: miiko.v1.MiikoService.TopicPost:output_type -> miiko.v1.TopicPostResponse
	14, // 23: miiko.v1.MiikoService.ProblemListGet:output_type -> miiko.v1.ProblemListGetResponse
	16, // 24: miiko.v1.MiikoService.ProblemGet:output_type -> miiko.v1.ProblemGetResponse
	18, // 25: miiko.v1.MiikoService.ProblemPost:output_type -> miiko.v1.ProblemPostResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_v1_miiko_proto_init() }
func file_v1_miiko_proto_init() {
	if File_v1_miiko_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_miiko_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Category); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Topic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Problem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryListGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryListGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CategoryPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicListGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicListGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemListGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemListGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemPostRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_miiko_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProblemPostResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_miiko_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_miiko_proto_goTypes,
		DependencyIndexes: file_v1_miiko_proto_depIdxs,
		EnumInfos:         file_v1_miiko_proto_enumTypes,
		MessageInfos:      file_v1_miiko_proto_msgTypes,
	}.Build()
	File_v1_miiko_proto = out.File
	file_v1_miiko_proto_rawDesc = nil
	file_v1_miiko_proto_goTypes = nil
	file_v1_miiko_proto_depIdxs = nil
}
