// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/health.proto (package miiko.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { HealthServiceCheckRequest, HealthServiceCheckResponse } from "./health_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service miiko.v1.HealthService
 */
export const HealthService = {
  typeName: "miiko.v1.HealthService",
  methods: {
    /**
     * @generated from rpc miiko.v1.HealthService.Check
     */
    check: {
      name: "Check",
      I: HealthServiceCheckRequest,
      O: HealthServiceCheckResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

