// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/miiko.proto (package miiko.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CategoryListGetRequest, CategoryListGetResponse, CategoryPostRequest, CategoryPostResponse, ProblemGetRequest, ProblemGetResponse, ProblemListGetRequest, ProblemListGetResponse, TopicListGetRequest, TopicListGetResponse, TopicPostRequest, TopicPostResponse } from "./miiko_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service miiko.v1.MiikoService
 */
export const MiikoService = {
  typeName: "miiko.v1.MiikoService",
  methods: {
    /**
     * @generated from rpc miiko.v1.MiikoService.CategoryListGet
     */
    categoryListGet: {
      name: "CategoryListGet",
      I: CategoryListGetRequest,
      O: CategoryListGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.CategoryPost
     */
    categoryPost: {
      name: "CategoryPost",
      I: CategoryPostRequest,
      O: CategoryPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.TopicListGet
     */
    topicListGet: {
      name: "TopicListGet",
      I: TopicListGetRequest,
      O: TopicListGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.TopicPost
     */
    topicPost: {
      name: "TopicPost",
      I: TopicPostRequest,
      O: TopicPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.ProblemListGet
     */
    problemListGet: {
      name: "ProblemListGet",
      I: ProblemListGetRequest,
      O: ProblemListGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.ProblemGet
     */
    problemGet: {
      name: "ProblemGet",
      I: ProblemGetRequest,
      O: ProblemGetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

