// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/miiko.proto (package miiko.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CategoryListGetRequest, CategoryListGetResponse, CategoryPostRequest, CategoryPostResponse, ProblemGetRequest, ProblemGetResponse, ProblemListGetRequest, ProblemListGetResponse, ProblemPostRequest, ProblemPostResponse, StatisticsGetRequest, StatisticsGetResponse, TopicGetRequest, TopicGetResponse, TopicListGetRequest, TopicListGetResponse, TopicPostRequest, TopicPostResponse, UrlGetRequest, UrlGetResponse } from "./miiko_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service miiko.v1.MiikoService
 */
export const MiikoService = {
  typeName: "miiko.v1.MiikoService",
  methods: {
    /**
     * @generated from rpc miiko.v1.MiikoService.CategoryListGet
     */
    categoryListGet: {
      name: "CategoryListGet",
      I: CategoryListGetRequest,
      O: CategoryListGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.CategoryPost
     */
    categoryPost: {
      name: "CategoryPost",
      I: CategoryPostRequest,
      O: CategoryPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.TopicListGet
     */
    topicListGet: {
      name: "TopicListGet",
      I: TopicListGetRequest,
      O: TopicListGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.TopicGet
     */
    topicGet: {
      name: "TopicGet",
      I: TopicGetRequest,
      O: TopicGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.TopicPost
     */
    topicPost: {
      name: "TopicPost",
      I: TopicPostRequest,
      O: TopicPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.ProblemListGet
     */
    problemListGet: {
      name: "ProblemListGet",
      I: ProblemListGetRequest,
      O: ProblemListGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.ProblemGet
     */
    problemGet: {
      name: "ProblemGet",
      I: ProblemGetRequest,
      O: ProblemGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.ProblemPost
     */
    problemPost: {
      name: "ProblemPost",
      I: ProblemPostRequest,
      O: ProblemPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.StatisticsGet
     */
    statisticsGet: {
      name: "StatisticsGet",
      I: StatisticsGetRequest,
      O: StatisticsGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.UrlGet
     */
    urlGet: {
      name: "UrlGet",
      I: UrlGetRequest,
      O: UrlGetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

