// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/miiko.proto (package miiko.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { CategoryGetResponse, CategoryPostRequest, CategoryPostResponse, TopicGetRequest, TopicGetResponse } from "./miiko_pb.ts";

/**
 * @generated from service miiko.v1.MiikoService
 */
export const MiikoService = {
  typeName: "miiko.v1.MiikoService",
  methods: {
    /**
     * @generated from rpc miiko.v1.MiikoService.CategoryGet
     */
    categoryGet: {
      name: "CategoryGet",
      I: Empty,
      O: CategoryGetResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.CategoryPost
     */
    categoryPost: {
      name: "CategoryPost",
      I: CategoryPostRequest,
      O: CategoryPostResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc miiko.v1.MiikoService.TopicGet
     */
    topicGet: {
      name: "TopicGet",
      I: TopicGetRequest,
      O: TopicGetResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

